# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mysql:
        image: 'mysql/mysql-server:latest'
        ports:
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'zerojudge'
        networks:
            - sail
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
            retries: 3
            timeout: 5s
    tomcat:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DB_PASSWD: 'root'
        image: zerojudge/tomcat
        ports:
            - '8080'
        networks:
            - sail
        depends_on:
            - mysql

networks:
    sail:
        driver: bridge
